version: "3.8"

services:
  app:
    build: ./monitoring-service
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=lc-monitoring
      - PORT=:8080
      - RPC_URL=https://rpc.fuse.io
      - NFT_CONTRACT_ADDRESS=0x9Dbe0138C9b547c9467b5a4Ca6b566D1F6A8B997
      - DELEGATE_CONTRACT_ADDRESS=0xf9689022f129aeb4495f6c33bacf4bcaba1f8fca
      - RIGHTS=0x4675736520456d626572204e6f6465204c6963656e7365000000000000000000
      - CHECK_NFT_INTERVAL=6
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --quiet --logpath /dev/null
    logging:
      driver: "none"

volumes:
  mongodb_data:
