# Default values for avail-light-client-monitoring-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

externalSecrets:
  secretStoreName: "external-secrets-hashicorp-vault"
  remoteRefKey: "fuseio/avail-light-client-monitoring-service"
  refreshInterval: "15s"
  secretKey:
    - mongo_uri
    - mongo_db

replicaCount: 1

image:
  repository: 743g6573.c1.va1.container-registry.ovh.us/fuseio/avail-light-client-monitoring-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

command: []

args: []

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsUser: 1000

securityContext:
  runAsGroup: 1000
  runAsUser: 1000

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: monitoring.avail.fuse.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: avail-light-client-monitoring-service-tls-certificate
      hosts:
        - monitoring.avail.fuse.io

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

configMap:
  port: ":8080"
  rpc_url: "https://rpc.fuse.io"
  nft_contract_address: "0x9Dbe0138C9b547c9467b5a4Ca6b566D1F6A8B997"
  delegate_contract_address: "0xf9689022f129aeb4495f6c33bacf4bcaba1f8fca"
  rights: "0x4675736520416d62657220546573746e6574204c6963656e7365000000000000"
  check_nft_interval: "6"

nodeSelector: {}

tolerations: []

affinity: {}
